// AUTO-GENERATED by scripts/gen-extraction-blueprint-types.mjs from
// scripts/extraction-blueprint.schema.json (a schemars dump of rust4pm's
// process_mining::core::event_data::object_centric::extraction model). Do not edit by hand --
// regenerate per scripts/gen-extraction-blueprint-schema-rs/README.md.
//
// This package intentionally does not depend on @r4pm/client (see dfg/index.tsx,
// oc-declare/index.tsx for the established precedent), so these types are generated straight
// from the Rust model's JSON Schema instead of imported from generated client bindings or
// hand-mirrored. Every serde-tagged shape here uses the Rust side's
// #[serde(tag = "type", rename_all = "kebab-case")] convention.

export type OCELAttributeType = "String" | "Time" | "Integer" | "Float" | "Boolean" | "Null";

export interface AttributeMapping {
  /**
   * Attribute name in the resulting log.
   */
  name: string;
  /**
   * Column to read.
   */
  source_column: string;
  /**
   * Declared attribute type, or `None` to take the catalog's type for `source_column`.
   */
  value_type?: OCELAttributeType | null;
}

export type MappingEntry =
  | {
      /**
       * Display label, also used to name this mapping in diagnostics.
       */
      label?: string | null;
      /**
       * The node whose rows this reads.
       */
      node: string;
      /**
       * What to produce.
       */
      target:
        | {
            /**
             * Event attributes.
             */
            attributes?: AttributeMapping[];
            /**
             * Event type.
             */
            event_type:
              | {
                  /**
                   * Column name.
                   */
                  column: string;
                  type: "column";
                }
              | {
                  type: "constant";
                  /**
                   * The value.
                   */
                  value: string;
                }
              | {
                  /**
                   * The template.
                   */
                  template: string;
                  type: "template";
                }
              | {
                  /**
                   * Parts, tried in order.
                   */
                  parts: ValueExpression[];
                  type: "coalesce";
                };
            /**
             * Event id. `None` assigns a UUID, which is not reproducible across runs and cannot
             * be compiled to a view.
             *
             * It is also what coalesces a fan-out. Reading a join of orders and their items gives
             * one row per item, so a `None` id makes one event per item; an id naming the order
             * makes one event per order, still related to every item, because the repeated rows
             * are counted as [`MappingStats::deduplicated`](super::report::MappingStats::deduplicated)
             * while `objects` below is emitted for each of them.
             */
            id?: ValueExpression | null;
            /**
             * Objects related to this event.
             */
            objects?: InlineObjectRef[];
            /**
             * When it happened.
             */
            timestamp:
              | {
                  /**
                   * How to read it. `None` means auto-detection.
                   */
                  format?: TimestampFormat | null;
                  /**
                   * Produces one text value from a row.
                   *
                   * Every position that becomes an identity -- entity ids, relation endpoints, type names,
                   * qualifiers -- uses this, and every variant propagates absence: if any input has no
                   * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
                   */
                  source:
                    | {
                        /**
                         * Column name.
                         */
                        column: string;
                        type: "column";
                      }
                    | {
                        type: "constant";
                        /**
                         * The value.
                         */
                        value: string;
                      }
                    | {
                        /**
                         * The template.
                         */
                        template: string;
                        type: "template";
                      }
                    | {
                        /**
                         * Parts, tried in order.
                         */
                        parts: ValueExpression[];
                        type: "coalesce";
                      };
                  type: "value";
                }
              | {
                  /**
                   * Where the date comes from, if anywhere.
                   */
                  date?: TimestampPart | null;
                  /**
                   * Where the time comes from, if anywhere.
                   */
                  time?: TimestampPart | null;
                  type: "components";
                };
            type: "event";
          }
        | {
            /**
             * Object attributes.
             */
            attributes?: AttributeMapping[];
            /**
             * Produces one text value from a row.
             *
             * Every position that becomes an identity -- entity ids, relation endpoints, type names,
             * qualifiers -- uses this, and every variant propagates absence: if any input has no
             * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
             */
            id:
              | {
                  /**
                   * Column name.
                   */
                  column: string;
                  type: "column";
                }
              | {
                  type: "constant";
                  /**
                   * The value.
                   */
                  value: string;
                }
              | {
                  /**
                   * The template.
                   */
                  template: string;
                  type: "template";
                }
              | {
                  /**
                   * Parts, tried in order.
                   */
                  parts: ValueExpression[];
                  type: "coalesce";
                };
            /**
             * Produces one text value from a row.
             *
             * Every position that becomes an identity -- entity ids, relation endpoints, type names,
             * qualifiers -- uses this, and every variant propagates absence: if any input has no
             * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
             */
            object_type:
              | {
                  /**
                   * Column name.
                   */
                  column: string;
                  type: "column";
                }
              | {
                  type: "constant";
                  /**
                   * The value.
                   */
                  value: string;
                }
              | {
                  /**
                   * The template.
                   */
                  template: string;
                  type: "template";
                }
              | {
                  /**
                   * Parts, tried in order.
                   */
                  parts: ValueExpression[];
                  type: "coalesce";
                };
            /**
             * When the attribute values below were observed. `None` records them as static
             * values stamped at the Unix epoch.
             */
            timestamp?: TimestampSource | null;
            type: "object";
          }
        | {
            event: EventEndpoint;
            object: ObjectEndpoint;
            /**
             * Relation qualifier.
             */
            qualifier?: ValueExpression | null;
            type: "e2o";
          }
        | {
            /**
             * Relation qualifier.
             */
            qualifier?: ValueExpression | null;
            source: ObjectEndpoint;
            target: ObjectEndpoint;
            type: "o2o";
          };
      /**
       * Only rows satisfying this produce anything. `None` accepts every row.
       */
      when?: Predicate | null;
      type: "single";
    }
  | {
      /**
       * Mappings, in priority order.
       */
      mappings: Mapping[];
      type: "ordered";
    };

export type ValueExpression =
  | {
      /**
       * Column name.
       */
      column: string;
      type: "column";
    }
  | {
      type: "constant";
      /**
       * The value.
       */
      value: string;
    }
  | {
      /**
       * The template.
       */
      template: string;
      type: "template";
    }
  | {
      /**
       * Parts, tried in order.
       */
      parts: ValueExpression[];
      type: "coalesce";
    };

export type TimestampFormat =
  | {
      type: "auto";
    }
  | {
      /**
       * The format.
       */
      format: string;
      type: "format-string";
    }
  | {
      type: "unix-seconds";
    }
  | {
      type: "unix-millis";
    };

export type TimestampSource =
  | {
      /**
       * How to read it. `None` means auto-detection.
       */
      format?: TimestampFormat | null;
      /**
       * Produces one text value from a row.
       *
       * Every position that becomes an identity -- entity ids, relation endpoints, type names,
       * qualifiers -- uses this, and every variant propagates absence: if any input has no
       * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
       */
      source:
        | {
            /**
             * Column name.
             */
            column: string;
            type: "column";
          }
        | {
            type: "constant";
            /**
             * The value.
             */
            value: string;
          }
        | {
            /**
             * The template.
             */
            template: string;
            type: "template";
          }
        | {
            /**
             * Parts, tried in order.
             */
            parts: ValueExpression[];
            type: "coalesce";
          };
      type: "value";
    }
  | {
      /**
       * Where the date comes from, if anywhere.
       */
      date?: TimestampPart | null;
      /**
       * Where the time comes from, if anywhere.
       */
      time?: TimestampPart | null;
      type: "components";
    };

export interface Blueprint {
  /**
   * How entity ids are rendered.
   */
  id_rendering?: "raw" | "type-prefixed";
  /**
   * The mappings.
   */
  mappings: MappingEntry[];
  /**
   * The row graph.
   */
  nodes: Node[];
  /**
   * What to do about a repeated object id.
   */
  on_duplicate_object?: "first-wins" | "error";
  /**
   * What to do about relations naming a missing entity.
   */
  on_missing_endpoint?: "drop" | "create" | "error";
  /**
   * Schema version. Checked against [`super::MODEL_VERSION`] during validation.
   */
  version: number;
}

export interface InlineObjectRef {
  object: ObjectEndpoint;
  /**
   * Relation qualifier.
   */
  qualifier?: ValueExpression | null;
}

export interface ObjectEndpoint {
  /**
   * Produces one text value from a row.
   *
   * Every position that becomes an identity -- entity ids, relation endpoints, type names,
   * qualifiers -- uses this, and every variant propagates absence: if any input has no
   * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
   */
  id:
    | {
        /**
         * Column name.
         */
        column: string;
        type: "column";
      }
    | {
        type: "constant";
        /**
         * The value.
         */
        value: string;
      }
    | {
        /**
         * The template.
         */
        template: string;
        type: "template";
      }
    | {
        /**
         * Parts, tried in order.
         */
        parts: ValueExpression[];
        type: "coalesce";
      };
  /**
   * The object's type. Required under [`IdRendering::TypePrefixed`] and under
   * [`MissingEndpointPolicy::Create`].
   */
  object_type?: ValueExpression | null;
  /**
   * Split the id cell into several ids, producing one relation per part.
   */
  split?: SplitSpec | null;
}

export interface SplitSpec {
  /**
   * The splitting rule.
   */
  kind:
    | {
        /**
         * The separator.
         */
        delimiter: string;
        type: "delimiter";
      }
    | {
        /**
         * The pattern.
         */
        pattern: string;
        type: "regex";
      };
  /**
   * Trim surrounding whitespace from each part.
   */
  trim: boolean;
}

export interface TimestampPart {
  /**
   * How to read it. `None` means auto-detection.
   */
  format?: TimestampFormat | null;
  /**
   * Produces one text value from a row.
   *
   * Every position that becomes an identity -- entity ids, relation endpoints, type names,
   * qualifiers -- uses this, and every variant propagates absence: if any input has no
   * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
   */
  source:
    | {
        /**
         * Column name.
         */
        column: string;
        type: "column";
      }
    | {
        type: "constant";
        /**
         * The value.
         */
        value: string;
      }
    | {
        /**
         * The template.
         */
        template: string;
        type: "template";
      }
    | {
        /**
         * Parts, tried in order.
         */
        parts: ValueExpression[];
        type: "coalesce";
      };
}

export interface EventEndpoint {
  /**
   * The event's type. Required under [`IdRendering::TypePrefixed`].
   */
  event_type?: ValueExpression | null;
  /**
   * Produces one text value from a row.
   *
   * Every position that becomes an identity -- entity ids, relation endpoints, type names,
   * qualifiers -- uses this, and every variant propagates absence: if any input has no
   * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
   */
  id:
    | {
        /**
         * Column name.
         */
        column: string;
        type: "column";
      }
    | {
        type: "constant";
        /**
         * The value.
         */
        value: string;
      }
    | {
        /**
         * The template.
         */
        template: string;
        type: "template";
      }
    | {
        /**
         * Parts, tried in order.
         */
        parts: ValueExpression[];
        type: "coalesce";
      };
}

export interface Mapping {
  /**
   * Display label, also used to name this mapping in diagnostics.
   */
  label?: string | null;
  /**
   * The node whose rows this reads.
   */
  node: string;
  /**
   * What to produce.
   */
  target:
    | {
        /**
         * Event attributes.
         */
        attributes?: AttributeMapping[];
        /**
         * Event type.
         */
        event_type:
          | {
              /**
               * Column name.
               */
              column: string;
              type: "column";
            }
          | {
              type: "constant";
              /**
               * The value.
               */
              value: string;
            }
          | {
              /**
               * The template.
               */
              template: string;
              type: "template";
            }
          | {
              /**
               * Parts, tried in order.
               */
              parts: ValueExpression[];
              type: "coalesce";
            };
        /**
         * Event id. `None` assigns a UUID, which is not reproducible across runs and cannot
         * be compiled to a view.
         *
         * It is also what coalesces a fan-out. Reading a join of orders and their items gives
         * one row per item, so a `None` id makes one event per item; an id naming the order
         * makes one event per order, still related to every item, because the repeated rows
         * are counted as [`MappingStats::deduplicated`](super::report::MappingStats::deduplicated)
         * while `objects` below is emitted for each of them.
         */
        id?: ValueExpression | null;
        /**
         * Objects related to this event.
         */
        objects?: InlineObjectRef[];
        /**
         * When it happened.
         */
        timestamp:
          | {
              /**
               * How to read it. `None` means auto-detection.
               */
              format?: TimestampFormat | null;
              /**
               * Produces one text value from a row.
               *
               * Every position that becomes an identity -- entity ids, relation endpoints, type names,
               * qualifiers -- uses this, and every variant propagates absence: if any input has no
               * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
               */
              source:
                | {
                    /**
                     * Column name.
                     */
                    column: string;
                    type: "column";
                  }
                | {
                    type: "constant";
                    /**
                     * The value.
                     */
                    value: string;
                  }
                | {
                    /**
                     * The template.
                     */
                    template: string;
                    type: "template";
                  }
                | {
                    /**
                     * Parts, tried in order.
                     */
                    parts: ValueExpression[];
                    type: "coalesce";
                  };
              type: "value";
            }
          | {
              /**
               * Where the date comes from, if anywhere.
               */
              date?: TimestampPart | null;
              /**
               * Where the time comes from, if anywhere.
               */
              time?: TimestampPart | null;
              type: "components";
            };
        type: "event";
      }
    | {
        /**
         * Object attributes.
         */
        attributes?: AttributeMapping[];
        /**
         * Produces one text value from a row.
         *
         * Every position that becomes an identity -- entity ids, relation endpoints, type names,
         * qualifiers -- uses this, and every variant propagates absence: if any input has no
         * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
         */
        id:
          | {
              /**
               * Column name.
               */
              column: string;
              type: "column";
            }
          | {
              type: "constant";
              /**
               * The value.
               */
              value: string;
            }
          | {
              /**
               * The template.
               */
              template: string;
              type: "template";
            }
          | {
              /**
               * Parts, tried in order.
               */
              parts: ValueExpression[];
              type: "coalesce";
            };
        /**
         * Produces one text value from a row.
         *
         * Every position that becomes an identity -- entity ids, relation endpoints, type names,
         * qualifiers -- uses this, and every variant propagates absence: if any input has no
         * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
         */
        object_type:
          | {
              /**
               * Column name.
               */
              column: string;
              type: "column";
            }
          | {
              type: "constant";
              /**
               * The value.
               */
              value: string;
            }
          | {
              /**
               * The template.
               */
              template: string;
              type: "template";
            }
          | {
              /**
               * Parts, tried in order.
               */
              parts: ValueExpression[];
              type: "coalesce";
            };
        /**
         * When the attribute values below were observed. `None` records them as static
         * values stamped at the Unix epoch.
         */
        timestamp?: TimestampSource | null;
        type: "object";
      }
    | {
        event: EventEndpoint;
        object: ObjectEndpoint;
        /**
         * Relation qualifier.
         */
        qualifier?: ValueExpression | null;
        type: "e2o";
      }
    | {
        /**
         * Relation qualifier.
         */
        qualifier?: ValueExpression | null;
        source: ObjectEndpoint;
        target: ObjectEndpoint;
        type: "o2o";
      };
  /**
   * Only rows satisfying this produce anything. `None` accepts every row.
   */
  when?: Predicate | null;
}

export interface Node {
  /**
   * Unique id, referenced by other nodes and by mappings.
   */
  id: string;
  /**
   * Display label. No semantic role.
   */
  label?: string | null;
  /**
   * The operation.
   */
  op:
    | {
        /**
         * Source id, resolved to a connection at execution time.
         */
        source_id: string;
        /**
         * Table name.
         */
        table: string;
        type: "source";
      }
    | {
        /**
         * The condition.
         */
        condition: Predicate;
        /**
         * Input node id.
         */
        input: string;
        type: "filter";
      }
    | {
        /**
         * Left input node id.
         */
        left: string;
        /**
         * Column pairs, as `(left column, right column)`.
         */
        on: [string, string][];
        /**
         * Right input node id.
         */
        right: string;
        type: "join";
      }
    | {
        /**
         * Input node ids.
         */
        inputs: string[];
        type: "union";
      };
}

export interface ColumnSchema {
  /**
   * The source's own type name, verbatim, for example `INTEGER` or `timestamp`.
   */
  col_type: string;
  /**
   * Column name.
   */
  name: string;
  /**
   * Whether the source permits `NULL` here.
   */
  nullable: boolean;
}

export type CompareOp = "eq" | "ne" | "lt" | "le" | "gt" | "ge";

export interface CompileError {
  /**
   * The mapping this is about, or `None` for a blueprint-level problem.
   */
  mapping?: MappingRef | null;
  /**
   * Why it could not be compiled.
   */
  reason:
    | {
        SynthesizedId: {
          /**
           * The absent field.
           */
          field: string;
        };
      }
    | {
        DynamicTypeName: {
          /**
           * Why no domain was available.
           */
          detail: string;
          /**
           * The position whose type is dynamic.
           */
          field: string;
        };
      }
    | {
        TypeDomainTooLarge: {
          /**
           * The cap.
           */
          cap: number;
          /**
           * The column the domain came from.
           */
          column: string;
          /**
           * How many values it has.
           */
          size: number;
        };
      }
    | {
        ReservedTypeName: {
          /**
           * The offending type name.
           */
          name: string;
        };
      }
    | {
        UnknownNode: {
          /**
           * The node id.
           */
          node: string;
        };
      }
    | {
        UnresolvedNodeSchema: {
          /**
           * The node id.
           */
          node: string;
        };
      }
    | {
        NodeCycle: {
          /**
           * A node id taking part in the cycle.
           */
          node: string;
        };
      }
    | {
        EmptyProjection: {
          /**
           * The node id.
           */
          node: string;
        };
      }
    | {
        EmptyUnion: {
          /**
           * The node id.
           */
          node: string;
        };
      }
    | {
        UnknownColumn: {
          /**
           * The column name.
           */
          column: string;
          /**
           * Which position referenced it.
           */
          field: string;
        };
      }
    | {
        UndeclaredColumnKind: {
          /**
           * The catalog's own type string.
           */
          col_type: string;
          /**
           * The column name.
           */
          column: string;
          /**
           * Which position referenced it.
           */
          field: string;
        };
      }
    | {
        UnstableIdentityRendering: {
          /**
           * The catalog's own type string.
           */
          col_type: string;
          /**
           * The column name.
           */
          column: string;
          /**
           * Which position referenced it.
           */
          field: string;
        };
      }
    | {
        UnstableDisplayRendering: {
          /**
           * The catalog's own type string.
           */
          col_type: string;
          /**
           * The column name.
           */
          column: string;
          /**
           * Which position referenced it.
           */
          field: string;
        };
      }
    | {
        ResidualTimestamp: {
          /**
           * What about it is residual.
           */
          detail: string;
        };
      }
    | {
        UndecidableJoinKey: {
          /**
           * The catalog's own type string.
           */
          col_type: string;
          /**
           * The column name.
           */
          column: string;
          /**
           * The join node's id.
           */
          node: string;
          /**
           * Which side the column is on.
           */
          side: string;
        };
      }
    | {
        UnportableRegex: {
          /**
           * Which construct made it unportable.
           */
          detail: string;
          /**
           * The pattern.
           */
          pattern: string;
        };
      }
    | {
        InvalidRegex: {
          /**
           * The compiler's message.
           */
          message: string;
          /**
           * The pattern.
           */
          pattern: string;
        };
      }
    | {
        InvalidTemplate: {
          /**
           * What is wrong with it.
           */
          reason: string;
          /**
           * The template text.
           */
          template: string;
        };
      }
    | {
        AttributeCoercion: {
          /**
           * The attribute name.
           */
          attribute: string;
          /**
           * The catalog's own type string.
           */
          col_type: string;
          /**
           * The source column.
           */
          column: string;
          /**
           * The declared OCEL attribute type.
           */
          declared: string;
        };
      }
    | {
        DynamicTypeAttributeConflict: {
          /**
           * The attribute name.
           */
          attribute: string;
        };
      }
    | {
        UnsupportedEmissionShape: {
          /**
           * The shape asked for.
           */
          shape: string;
        };
      }
    | {
        ViewCycle: {
          /**
           * The relation's name.
           */
          view: string;
        };
      }
    | {
        Invalid: {
          /**
           * The rendered validation error.
           */
          detail: string;
        };
      };
}

export interface MappingRef {
  /**
   * What this mapping produces, derived from its target: `event "appoint officer"`,
   * `event -> object relation`, and so on. Present whether or not a `label` was typed.
   */
  describes: string;
  /**
   * Position in the desugared, flattened mapping list this run executed.
   */
  index: number;
  /**
   * The mapping's own label, if it has one.
   */
  label?: string | null;
  /**
   * The JSON path of the authored entry this mapping came from -- see
   * [`desugar_with_paths`](super::desugar::desugar_with_paths) -- so a diagnostic points at
   * what the author wrote rather than a position in the flattened list.
   */
  path: string;
}

export type SqlDialect = "DuckDb" | "Postgres";

export type EmissionShape = "PerType" | "Consolidated";

export interface CompiledOcel {
  dialect: SqlDialect;
  errors: CompileError[];
  probes: Probe[];
  shape: EmissionShape;
  views: ViewDef[];
}

export interface Probe {
  /**
   * What it guards.
   */
  kind:
    | "AmbiguousObjectIdentity"
    | "AmbiguousEventIdentity"
    | "AmbiguousStaticObjectAttributes"
    | {
        StaleTypeDomain: {
          /**
           * The column the domain came from.
           */
          column: string;
        };
      };
  /**
   * The mapping this is about, or `None` for a whole-log check.
   */
  mapping?: MappingRef | null;
  /**
   * The check itself, as a `SELECT` returning zero rows when the guard holds.
   */
  sql: string;
}

export interface ViewDef {
  /**
   * A bare `SELECT` body with no `CREATE` wrapper, so the same text serves a view, a CTE and
   * a `CREATE TABLE AS`.
   */
  body: string;
  /**
   * The relation's name, unquoted.
   */
  name: string;
}

export type DropReason =
  | "UnresolvedEndpoint"
  | "UnparseableTimestamp"
  | "MissingTimestamp"
  | "NullOrUnrenderableId"
  | "PredicateExcluded"
  | "IdTypeCollision";

export type DuplicateObjectPolicy = "first-wins" | "error";

export interface ExtractionCatalog {
  /**
   * Column domains, keyed by source id, then table name, then column name.
   */
  domains: {
    [k: string]: {
      [k: string]: {
        [k: string]: string[];
      };
    };
  };
  /**
   * A handful of real rows per table, keyed by source id then table name, to show a person
   * what the data looks like.
   *
   * Deliberately unreachable through the [`Catalog`] trait: unlike
   * [`domains`](ExtractionCatalog::domains), a preview is incomplete, so compiling from one
   * would emit views only for the types that happened to appear first.
   */
  previews?: {
    [k: string]: {
      [k: string]: TablePreview;
    };
  };
  /**
   * Table schemas, keyed by source id then table name.
   */
  tables: {
    [k: string]: {
      [k: string]: TableSchema;
    };
  };
}

export interface TablePreview {
  /**
   * Column names, in the order the rows are aligned to.
   */
  columns: string[];
  /**
   * Rows, each the same length as `columns`.
   */
  rows: (string | null)[][];
}

export interface TableSchema {
  /**
   * Columns, keyed by name.
   */
  columns: {
    [k: string]: ColumnSchema;
  };
  /**
   * Table name.
   */
  name: string;
}

export type ExtractionError =
  | {
      Invalid: ValidationError[];
    }
  | {
      MissingProvider: {
        /**
         * The missing source id.
         */
        source_id: string;
      };
    }
  | {
      InvalidRegex: {
        /**
         * The compiler's message.
         */
        message: string;
        /**
         * The offending pattern.
         */
        pattern: string;
      };
    }
  | {
      JoinKeyColumnMissing: {
        /**
         * The key column, as named on that side.
         */
        column: string;
        /**
         * The `Join` node.
         */
        node: string;
        /**
         * `"left"` or `"right"`.
         */
        side: string;
      };
    }
  | {
      Provider: {
        /**
         * The node being read when the failure happened.
         */
        node: string;
        /**
         * The underlying error.
         */
        source:
          | {
              UnknownTable: {
                /**
                 * The table name.
                 */
                table: string;
              };
            }
          | {
              UnknownColumn: {
                /**
                 * The column name.
                 */
                column: string;
                /**
                 * The table name.
                 */
                table: string;
              };
            }
          | "QueryUnsupported"
          | {
              Backend: {
                /**
                 * The backend's error message.
                 */
                message: string;
                /**
                 * The table being read when the failure happened.
                 */
                table: string;
              };
            };
      };
    }
  | {
      Sink: {
        /**
         * What was being added when the failure happened.
         */
        context: string;
        /**
         * The underlying error.
         */
        source:
          | {
              DuplicateEvent: {
                /**
                 * The repeated id.
                 */
                id: string;
              };
            }
          | {
              DuplicateObject: {
                /**
                 * The repeated id.
                 */
                id: string;
              };
            }
          | {
              IdTypeCollision: {
                /**
                 * The contested id.
                 */
                id: string;
              };
            }
          | {
              UnknownType: {
                /**
                 * `"event"` or `"object"`.
                 */
                kind: string;
                /**
                 * The undeclared type name.
                 */
                name: string;
              };
            }
          | "InvalidRef"
          | {
              Backend: string;
            };
      };
    }
  | {
      IdTypeCollision: {
        /**
         * The contested id.
         */
        id: string;
        mapping: MappingRef;
        /**
         * The type this row wanted the id for. The type that already holds it is whatever the
         * sink reports for that id.
         */
        requested_type: string;
      };
    }
  | {
      ConflictingAttributeType: {
        /**
         * The attribute.
         */
        attribute: string;
        /**
         * The type the later declaration gave it.
         */
        conflicting: "String" | "Time" | "Integer" | "Float" | "Boolean" | "Null";
        /**
         * The type it was declared with first.
         */
        declared: "String" | "Time" | "Integer" | "Float" | "Boolean" | "Null";
        /**
         * `"event"` or `"object"`.
         */
        kind: string;
        /**
         * The entity type.
         */
        type_name: string;
      };
    }
  | {
      DuplicateObject: {
        /**
         * The repeated id.
         */
        id: string;
        mapping: MappingRef;
      };
    }
  | {
      MissingEndpoint: {
        /**
         * Which endpoint (`"event"`, `"object"`, `"source"`, `"target"`, ...).
         */
        endpoint: string;
        /**
         * The unresolved id.
         */
        id: string;
        mapping: MappingRef;
      };
    }
  | {
      MissingEndpointsAtFinalize: {
        /**
         * How many relations the sink could not resolve. Equals the number of
         * [`MissingEndpoint`](Self::MissingEndpoint) errors an eager sink reports for the same
         * run for an `E2O`/`O2O` endpoint or a `Target::Event`'s inline reference resolved via
         * [`resolve_object_endpoint`](super::mapping_exec::resolve_object_endpoint) --
         * **not** universally: an inline reference on a `Target::Event` whose own event this run
         * dropped is reported by an eager sink as [`DropReason::UnresolvedEndpoint`] on that
         * mapping, with no [`MissingEndpoint`] error pushed at all (there is no endpoint left to
         * resolve), while a deferring sink -- which cannot know at the call site that the event
         * will not exist -- stages the reference regardless and counts it here at finalize. This
         * count can therefore exceed the eager sink's `MissingEndpoint` tally by exactly that
         * many references.
         */
        count: number;
      };
    };

export type ValidationError =
  | {
      /**
       * The blueprint's version.
       */
      found: number;
      /**
       * The newest version this build reads.
       */
      supported: number;
      type: "unsupported-version";
    }
  | {
      /**
       * The repeated id.
       */
      id: string;
      type: "duplicate-node-id";
    }
  | {
      /**
       * Who referred to it.
       */
      from: string;
      /**
       * The missing id.
       */
      id: string;
      type: "unknown-node-ref";
    }
  | {
      /**
       * One node id participating in the cycle.
       */
      id: string;
      type: "node-cycle";
    }
  | {
      /**
       * The source id.
       */
      source_id: string;
      type: "unknown-source";
    }
  | {
      /**
       * The source id.
       */
      source_id: string;
      /**
       * The table name.
       */
      table: string;
      type: "unknown-table";
    }
  | {
      /**
       * The column name.
       */
      column: string;
      /**
       * The node whose rows were being read.
       */
      node: string;
      type: "unknown-column";
    }
  | {
      /**
       * Which endpoint.
       */
      endpoint: string;
      /**
       * Which mapping, by label or index.
       */
      mapping: string;
      type: "missing-type-for-prefixing";
    }
  | {
      /**
       * Which endpoint.
       */
      endpoint: string;
      /**
       * Which mapping, by label or index.
       */
      mapping: string;
      type: "missing-type-for-create";
    }
  | {
      /**
       * The node id.
       */
      node: string;
      type: "empty-union";
    }
  | {
      /**
       * The compiler's message.
       */
      message: string;
      /**
       * The pattern.
       */
      pattern: string;
      type: "invalid-regex";
    }
  | {
      /**
       * What is wrong with it.
       */
      reason: string;
      /**
       * The template text.
       */
      template: string;
      type: "invalid-template";
    };

export interface ExtractionReport {
  /**
   * Non-fatal problems collected while running -- a policy configured to error
   * (`on_duplicate_object: Error`, `on_missing_endpoint: Error`) or a sink failure on one
   * relation. Extraction continues past these; see [`ExtractionError`] for what aborts it
   * instead.
   */
  errors: ExtractionError[];
  finalize: FinalizeReport;
  /**
   * One entry per mapping executed, in **desugared blueprint order** -- the order the author
   * wrote the mappings in, with each ordered group expanded in place. Deliberately not
   * execution order: execution is multi-pass and grouped by node (see
   * [`extract`](super::extract::extract)), so there is no single linear order to report, and
   * a diagnostic is far more useful indexed by what the author wrote. Each entry's
   * [`MappingRef::path`] names that authored entry outright.
   */
  per_mapping: MappingStats[];
  /**
   * The running total of rows every `Join`/`Union` materialisation this run performed
   * produced -- summed across materialisations, **not** a peak: a run that materialises two
   * nodes of a thousand rows each reports two thousand, even though the two never had to be
   * live at the same moment. It is an upper bound on peak buffered rows, not the peak itself.
   * (A cached materialisation is counted once, when it is computed, not again per reader.)
   *
   * Includes the `Source`/`Filter` rows that fed a `Join`/`Union`, since those materialise
   * too the moment one needs them as an input; see invariant I1 on
   * [`extract`](super::extract::extract). Zero when no mapping's node graph contains a `Join`
   * or `Union`, since a pure `Source -> Filter` chain streams and never buffers a row past
   * the one being processed -- which is what makes zero here a meaningful witness that the
   * run streamed.
   */
  rows_materialized: number;
  /**
   * Where the run's wall-clock time went.
   *
   * `None` from [`extract`](super::extract::extract) itself, which is handed a catalog and a
   * set of open providers and so has no idea what it cost to obtain them. The runner that owns
   * the connections fills this in; the `extraction-dbcon` bindings do. Kept out of `extract` for a
   * second reason too: `std::time::Instant` panics on `wasm32-unknown-unknown`, and this crate
   * builds for wasm.
   */
  timing?: ExtractionTiming | null;
}

export interface FinalizeReport {
  /**
   * Repeated entity ids removed at finalize -- a deferring sink's share of
   * [`MappingStats::deduplicated`](super::report::MappingStats::deduplicated), which it could
   * not detect while writing.
   */
  duplicates_removed: number;
  /**
   * Objects synthesised at finalize under `on_missing_endpoint: Create`, for deferred
   * endpoints that turned out not to exist.
   */
  objects_created: number;
  /**
   * Relations written against a [`Resolution::Deferred`] endpoint that resolved to a real
   * entity at finalize.
   */
  resolved_relations: number;
  /**
   * Relations whose deferred endpoint did not resolve. These are what a sink answering
   * immediately would have counted per mapping as
   * [`DropReason::UnresolvedEndpoint`](super::report::DropReason::UnresolvedEndpoint);
   * `on_missing_endpoint` decided what happened to them (dropped, or their object created).
   */
  unresolved_endpoints: number;
}

export interface MappingStats {
  /**
   * Rows that tried to create an entity **the sink already had**. Not a loss: an object mapping
   * at event grain names the same object on every row by design. See
   * [`DuplicateObjectPolicy::Error`](super::blueprint::DuplicateObjectPolicy::Error) for what
   * turns a repeat into a loss instead.
   *
   * # Exactly what is counted
   *
   * One increment per row whose entity-creating call found the entity already present:
   *
   * * a [`Target::Object`](super::blueprint::Target::Object) row whose
   *   [`resolve_object`](super::sink::ExtractionSink::resolve_object) answered
   *   [`Exists`](super::sink::Resolution::Exists), or whose
   *   [`add_object`](super::sink::ExtractionSink::add_object) was refused with
   *   [`SinkError::DuplicateObject`](super::sink::SinkError::DuplicateObject) -- the same event
   *   seen through an eager and a deferring sink respectively, which is why both report the same
   *   number;
   * * a [`Target::Event`](super::blueprint::Target::Event) row whose `add_event` was refused
   *   with [`SinkError::DuplicateEvent`](super::sink::SinkError::DuplicateEvent).
   *
   * **Including a repeat across two mappings**, which is a change in meaning from "rows that
   * named an entity *this mapping* had already emitted". A second mapping naming an id a first
   * mapping created now counts one deduplication, where it used to count none. That distinction
   * needed one id set per mapping holding every id it named -- the last per-run structure whose
   * size tracked the data -- and it could never have been made to agree across sinks anyway: a
   * sink that answers [`Deferred`](super::sink::Resolution::Deferred) to every ask cannot say
   * whose object it already had.
   *
   * # And what is not
   *
   * **Resolving a relation endpoint is never counted**, so an `E2O`/`O2O` mapping reports zero
   * however often its rows repeat an id. Finding an endpoint that already exists is the normal
   * successful case, not a deduplication -- counting it made a healthy `E2O` mapping over `n`
   * rows report `n` deduplications (and `2n` for `O2O`) while nothing had been deduplicated at
   * all. Counting only the repeats among them is what the per-mapping id set used to buy, and it
   * went with it: a case-centric blueprint whose single event mapping creates its case objects
   * through an inline reference used to report `rows - distinct cases` here and now reports
   * zero. The objects are unaffected; only this counter is. A blueprint that wants that number
   * reported can name the cases with a [`Target::Object`](super::blueprint::Target::Object)
   * mapping, which is what [`FlatEventTable`](super::case_centric::FlatEventTable) already adds
   * as soon as there are case attributes.
   */
  deduplicated: number;
  /**
   * Rows dropped, by reason. A row that matches several reasons at once (rare) is counted
   * once, under the first one detected.
   */
  dropped: {
    [k: string]: number;
  };
  /**
   * Entities or relations this mapping *handed to the sink*.
   *
   * # Not "survived the run", for a sink that defers resolution
   *
   * For an eager sink ([`SlimOcelSink`](super::slim_sink::SlimOcelSink)) the two coincide:
   * a relation whose endpoint does not exist is refused at the call site, so it is counted
   * under [`DropReason::UnresolvedEndpoint`] and never here.
   *
   * A sink that answers [`Resolution::Deferred`](super::sink::Resolution::Deferred) --
   * [`DuckDbSink`](super::duckdb_sink::DuckDbSink) -- has no id index to refuse with, so the
   * relation is written, counted here, and only deleted at
   * [`finalize`](super::sink::ExtractionSink::finalize). The same dangling `E2O` therefore
   * reads as
   *
   * | | eager | deferring |
   * |---|---|---|
   * | `entities_emitted` | 0 | 1 |
   * | `dropped[UnresolvedEndpoint]` | 1 | absent |
   * | [`FinalizeReport::unresolved_endpoints`](super::sink::FinalizeReport) | 0 | 1 |
   *
   * This is the same reporting shift [`DuckDbSink`]'s own docs describe for `dropped`, seen
   * from the other side: the loss is reported in bulk at finalize because the mapping that
   * named the endpoint is long gone by then. Both logs still have the same contents.
   *
   * To compare two sinks, or to count what a run actually produced, subtract
   * `ExtractionReport::finalize.unresolved_endpoints` from the run's total rather than
   * reading a single mapping's counter -- per-mapping attribution of a deferred loss does not
   * exist, by construction.
   *
   * [`DuckDbSink`]: super::duckdb_sink::DuckDbSink
   */
  entities_emitted: number;
  mapping: MappingRef;
  /**
   * Rows the mapping's node produced, before `when` was applied.
   */
  rows_read: number;
}

export interface ExtractionTiming {
  /**
   * Connecting to each source and reading its schema. Zero when the caller supplied a catalog.
   */
  discovery_ms: number;
  /**
   * Reading rows and emitting entities: `extract` itself.
   */
  extraction_ms: number;
}

export type IdRendering = "raw" | "type-prefixed";

export type Literal =
  | boolean
  | number
  | string
  | {
      /**
       * The instant.
       */
      timestamp: string;
    };

export type MissingEndpointPolicy = "drop" | "create" | "error";

export type NodeOp =
  | {
      /**
       * Source id, resolved to a connection at execution time.
       */
      source_id: string;
      /**
       * Table name.
       */
      table: string;
      type: "source";
    }
  | {
      /**
       * The condition.
       */
      condition: Predicate;
      /**
       * Input node id.
       */
      input: string;
      type: "filter";
    }
  | {
      /**
       * Left input node id.
       */
      left: string;
      /**
       * Column pairs, as `(left column, right column)`.
       */
      on: [string, string][];
      /**
       * Right input node id.
       */
      right: string;
      type: "join";
    }
  | {
      /**
       * Input node ids.
       */
      inputs: string[];
      type: "union";
    };

export type Operand =
  | {
      /**
       * Column name.
       */
      column: string;
      type: "column";
    }
  | {
      type: "literal";
      /**
       * The literal.
       */
      value:
        | boolean
        | number
        | string
        | {
            /**
             * The instant.
             */
            timestamp: string;
          };
    };

export type Predicate =
  | {
      /**
       * Conditions.
       */
      conditions: Predicate[];
      type: "and";
    }
  | {
      /**
       * Conditions.
       */
      conditions: Predicate[];
      type: "or";
    }
  | {
      /**
       * The negated condition.
       */
      condition: Predicate;
      type: "not";
    }
  | {
      /**
       * Left side.
       */
      left:
        | {
            /**
             * Column name.
             */
            column: string;
            type: "column";
          }
        | {
            type: "literal";
            /**
             * The literal.
             */
            value:
              | boolean
              | number
              | string
              | {
                  /**
                   * The instant.
                   */
                  timestamp: string;
                };
          };
      /**
       * Operator.
       */
      op: "eq" | "ne" | "lt" | "le" | "gt" | "ge";
      /**
       * Right side.
       */
      right:
        | {
            /**
             * Column name.
             */
            column: string;
            type: "column";
          }
        | {
            type: "literal";
            /**
             * The literal.
             */
            value:
              | boolean
              | number
              | string
              | {
                  /**
                   * The instant.
                   */
                  timestamp: string;
                };
          };
      type: "compare";
    }
  | {
      /**
       * Column name.
       */
      column: string;
      type: "is-null";
    }
  | {
      /**
       * Column name.
       */
      column: string;
      type: "is-empty";
    }
  | {
      /**
       * Column name.
       */
      column: string;
      /**
       * Regular expression.
       */
      regex: string;
      type: "matches";
    }
  | {
      /**
       * Column name.
       */
      column: string;
      type: "in";
      /**
       * Accepted values.
       */
      values: Literal[];
    };

export type ProbeKind =
  | "AmbiguousObjectIdentity"
  | "AmbiguousEventIdentity"
  | "AmbiguousStaticObjectAttributes"
  | {
      StaleTypeDomain: {
        /**
         * The column the domain came from.
         */
        column: string;
      };
    };

export type ProviderError =
  | {
      UnknownTable: {
        /**
         * The table name.
         */
        table: string;
      };
    }
  | {
      UnknownColumn: {
        /**
         * The column name.
         */
        column: string;
        /**
         * The table name.
         */
        table: string;
      };
    }
  | "QueryUnsupported"
  | {
      Backend: {
        /**
         * The backend's error message.
         */
        message: string;
        /**
         * The table being read when the failure happened.
         */
        table: string;
      };
    };

export type RejectReason =
  | {
      SynthesizedId: {
        /**
         * The absent field.
         */
        field: string;
      };
    }
  | {
      DynamicTypeName: {
        /**
         * Why no domain was available.
         */
        detail: string;
        /**
         * The position whose type is dynamic.
         */
        field: string;
      };
    }
  | {
      TypeDomainTooLarge: {
        /**
         * The cap.
         */
        cap: number;
        /**
         * The column the domain came from.
         */
        column: string;
        /**
         * How many values it has.
         */
        size: number;
      };
    }
  | {
      ReservedTypeName: {
        /**
         * The offending type name.
         */
        name: string;
      };
    }
  | {
      UnknownNode: {
        /**
         * The node id.
         */
        node: string;
      };
    }
  | {
      UnresolvedNodeSchema: {
        /**
         * The node id.
         */
        node: string;
      };
    }
  | {
      NodeCycle: {
        /**
         * A node id taking part in the cycle.
         */
        node: string;
      };
    }
  | {
      EmptyProjection: {
        /**
         * The node id.
         */
        node: string;
      };
    }
  | {
      EmptyUnion: {
        /**
         * The node id.
         */
        node: string;
      };
    }
  | {
      UnknownColumn: {
        /**
         * The column name.
         */
        column: string;
        /**
         * Which position referenced it.
         */
        field: string;
      };
    }
  | {
      UndeclaredColumnKind: {
        /**
         * The catalog's own type string.
         */
        col_type: string;
        /**
         * The column name.
         */
        column: string;
        /**
         * Which position referenced it.
         */
        field: string;
      };
    }
  | {
      UnstableIdentityRendering: {
        /**
         * The catalog's own type string.
         */
        col_type: string;
        /**
         * The column name.
         */
        column: string;
        /**
         * Which position referenced it.
         */
        field: string;
      };
    }
  | {
      UnstableDisplayRendering: {
        /**
         * The catalog's own type string.
         */
        col_type: string;
        /**
         * The column name.
         */
        column: string;
        /**
         * Which position referenced it.
         */
        field: string;
      };
    }
  | {
      ResidualTimestamp: {
        /**
         * What about it is residual.
         */
        detail: string;
      };
    }
  | {
      UndecidableJoinKey: {
        /**
         * The catalog's own type string.
         */
        col_type: string;
        /**
         * The column name.
         */
        column: string;
        /**
         * The join node's id.
         */
        node: string;
        /**
         * Which side the column is on.
         */
        side: string;
      };
    }
  | {
      UnportableRegex: {
        /**
         * Which construct made it unportable.
         */
        detail: string;
        /**
         * The pattern.
         */
        pattern: string;
      };
    }
  | {
      InvalidRegex: {
        /**
         * The compiler's message.
         */
        message: string;
        /**
         * The pattern.
         */
        pattern: string;
      };
    }
  | {
      InvalidTemplate: {
        /**
         * What is wrong with it.
         */
        reason: string;
        /**
         * The template text.
         */
        template: string;
      };
    }
  | {
      AttributeCoercion: {
        /**
         * The attribute name.
         */
        attribute: string;
        /**
         * The catalog's own type string.
         */
        col_type: string;
        /**
         * The source column.
         */
        column: string;
        /**
         * The declared OCEL attribute type.
         */
        declared: string;
      };
    }
  | {
      DynamicTypeAttributeConflict: {
        /**
         * The attribute name.
         */
        attribute: string;
      };
    }
  | {
      UnsupportedEmissionShape: {
        /**
         * The shape asked for.
         */
        shape: string;
      };
    }
  | {
      ViewCycle: {
        /**
         * The relation's name.
         */
        view: string;
      };
    }
  | {
      Invalid: {
        /**
         * The rendered validation error.
         */
        detail: string;
      };
    };

export type SinkError =
  | {
      DuplicateEvent: {
        /**
         * The repeated id.
         */
        id: string;
      };
    }
  | {
      DuplicateObject: {
        /**
         * The repeated id.
         */
        id: string;
      };
    }
  | {
      IdTypeCollision: {
        /**
         * The contested id.
         */
        id: string;
      };
    }
  | {
      UnknownType: {
        /**
         * `"event"` or `"object"`.
         */
        kind: string;
        /**
         * The undeclared type name.
         */
        name: string;
      };
    }
  | "InvalidRef"
  | {
      Backend: string;
    };

export type SplitKind =
  | {
      /**
       * The separator.
       */
      delimiter: string;
      type: "delimiter";
    }
  | {
      /**
       * The pattern.
       */
      pattern: string;
      type: "regex";
    };

export type Target =
  | {
      /**
       * Event attributes.
       */
      attributes?: AttributeMapping[];
      /**
       * Event type.
       */
      event_type:
        | {
            /**
             * Column name.
             */
            column: string;
            type: "column";
          }
        | {
            type: "constant";
            /**
             * The value.
             */
            value: string;
          }
        | {
            /**
             * The template.
             */
            template: string;
            type: "template";
          }
        | {
            /**
             * Parts, tried in order.
             */
            parts: ValueExpression[];
            type: "coalesce";
          };
      /**
       * Event id. `None` assigns a UUID, which is not reproducible across runs and cannot
       * be compiled to a view.
       *
       * It is also what coalesces a fan-out. Reading a join of orders and their items gives
       * one row per item, so a `None` id makes one event per item; an id naming the order
       * makes one event per order, still related to every item, because the repeated rows
       * are counted as [`MappingStats::deduplicated`](super::report::MappingStats::deduplicated)
       * while `objects` below is emitted for each of them.
       */
      id?: ValueExpression | null;
      /**
       * Objects related to this event.
       */
      objects?: InlineObjectRef[];
      /**
       * When it happened.
       */
      timestamp:
        | {
            /**
             * How to read it. `None` means auto-detection.
             */
            format?: TimestampFormat | null;
            /**
             * Produces one text value from a row.
             *
             * Every position that becomes an identity -- entity ids, relation endpoints, type names,
             * qualifiers -- uses this, and every variant propagates absence: if any input has no
             * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
             */
            source:
              | {
                  /**
                   * Column name.
                   */
                  column: string;
                  type: "column";
                }
              | {
                  type: "constant";
                  /**
                   * The value.
                   */
                  value: string;
                }
              | {
                  /**
                   * The template.
                   */
                  template: string;
                  type: "template";
                }
              | {
                  /**
                   * Parts, tried in order.
                   */
                  parts: ValueExpression[];
                  type: "coalesce";
                };
            type: "value";
          }
        | {
            /**
             * Where the date comes from, if anywhere.
             */
            date?: TimestampPart | null;
            /**
             * Where the time comes from, if anywhere.
             */
            time?: TimestampPart | null;
            type: "components";
          };
      type: "event";
    }
  | {
      /**
       * Object attributes.
       */
      attributes?: AttributeMapping[];
      /**
       * Produces one text value from a row.
       *
       * Every position that becomes an identity -- entity ids, relation endpoints, type names,
       * qualifiers -- uses this, and every variant propagates absence: if any input has no
       * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
       */
      id:
        | {
            /**
             * Column name.
             */
            column: string;
            type: "column";
          }
        | {
            type: "constant";
            /**
             * The value.
             */
            value: string;
          }
        | {
            /**
             * The template.
             */
            template: string;
            type: "template";
          }
        | {
            /**
             * Parts, tried in order.
             */
            parts: ValueExpression[];
            type: "coalesce";
          };
      /**
       * Produces one text value from a row.
       *
       * Every position that becomes an identity -- entity ids, relation endpoints, type names,
       * qualifiers -- uses this, and every variant propagates absence: if any input has no
       * [`Value::canonical_string`], the whole expression is `None` and the caller drops the row.
       */
      object_type:
        | {
            /**
             * Column name.
             */
            column: string;
            type: "column";
          }
        | {
            type: "constant";
            /**
             * The value.
             */
            value: string;
          }
        | {
            /**
             * The template.
             */
            template: string;
            type: "template";
          }
        | {
            /**
             * Parts, tried in order.
             */
            parts: ValueExpression[];
            type: "coalesce";
          };
      /**
       * When the attribute values below were observed. `None` records them as static
       * values stamped at the Unix epoch.
       */
      timestamp?: TimestampSource | null;
      type: "object";
    }
  | {
      event: EventEndpoint;
      object: ObjectEndpoint;
      /**
       * Relation qualifier.
       */
      qualifier?: ValueExpression | null;
      type: "e2o";
    }
  | {
      /**
       * Relation qualifier.
       */
      qualifier?: ValueExpression | null;
      source: ObjectEndpoint;
      target: ObjectEndpoint;
      type: "o2o";
    };
